#!/usr/bin/env bash
# Rebuild the MarmotKit bindings from the darkmatter Rust workspace and
# re-vendor them into this macOS app.
#
# Usage:
#   ./scripts/sync-bindings.sh
#   DARKMATTER_DIR=/path/to/darkmatter ./scripts/sync-bindings.sh

set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DARKMATTER_DIR="${DARKMATTER_DIR:-$HOME/code/darkmatter}"

CRATE_DIR="$DARKMATTER_DIR/crates/marmot-uniffi"
TARGET_DIR="$DARKMATTER_DIR/target"
VENDOR_DIR="$APP_DIR/Vendored/MarmotKit"
BUILD_DIR="$(mktemp -d "${TMPDIR:-/tmp}/marmotkit-macos.XXXXXX")"
trap 'rm -rf "$BUILD_DIR"' EXIT

CRATE_NAME="marmot-uniffi"
LIB_BASENAME="marmot_uniffi"
FRAMEWORK_NAME="MarmotKit"

if [[ ! -d "$CRATE_DIR" ]]; then
    echo "error: can't find marmot-uniffi crate at $CRATE_DIR" >&2
    echo "       set DARKMATTER_DIR to point at the darkmatter repo." >&2
    exit 1
fi

export PATH="$HOME/.cargo/bin:$PATH"

mkdir -p "$BUILD_DIR/headers" "$BUILD_DIR/swift" "$VENDOR_DIR/Sources/MarmotKit"

echo "==> Building host MarmotKit artifacts from $DARKMATTER_DIR"
(
    cd "$DARKMATTER_DIR"
    cargo build --release -p "$CRATE_NAME"
    cargo run --release -p "$CRATE_NAME" --features cli --bin uniffi-bindgen -- \
      generate \
      --library "$TARGET_DIR/release/lib${LIB_BASENAME}.dylib" \
      --language swift \
      --out-dir "$BUILD_DIR/swift"
)

echo "==> Staging headers + modulemap"
cp "$BUILD_DIR/swift/${LIB_BASENAME}FFI.h" "$BUILD_DIR/headers/"
cp "$BUILD_DIR/swift/${LIB_BASENAME}FFI.modulemap" "$BUILD_DIR/headers/module.modulemap"

echo "==> Creating macOS $FRAMEWORK_NAME.xcframework"
rm -rf "$VENDOR_DIR/$FRAMEWORK_NAME.xcframework"
xcodebuild -create-xcframework \
  -library "$TARGET_DIR/release/lib${LIB_BASENAME}.a" \
  -headers "$BUILD_DIR/headers" \
  -output "$VENDOR_DIR/$FRAMEWORK_NAME.xcframework"

echo "==> Copying generated Swift bindings"
cp "$BUILD_DIR/swift/${LIB_BASENAME}.swift" "$VENDOR_DIR/Sources/MarmotKit/$FRAMEWORK_NAME.swift"

echo "==> Stamping MARMOT_VERSION"
DM_SHA="$(git -C "$DARKMATTER_DIR" rev-parse --short HEAD)"
DM_BRANCH="$(git -C "$DARKMATTER_DIR" rev-parse --abbrev-ref HEAD)"
DM_DIRTY=""
if ! git -C "$DARKMATTER_DIR" diff --quiet || ! git -C "$DARKMATTER_DIR" diff --cached --quiet; then
    DM_DIRTY="-dirty"
fi
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$VENDOR_DIR/MARMOT_VERSION" <<EOF
darkmatter-sha: ${DM_SHA}${DM_DIRTY}
darkmatter-branch: ${DM_BRANCH}
built-at: ${BUILT_AT}
uniffi-version: 0.28.3
macos-targets: aarch64-apple-darwin

Notes:
- Regenerate with: whitenoise-mac/scripts/sync-bindings.sh
- A "-dirty" suffix means the darkmatter working tree had uncommitted
  changes when this bundle was built.
EOF

cat > "$VENDOR_DIR/Sources/MarmotKit/MarmotKitVersion.swift" <<EOF
import Foundation

/// Build-time provenance for this vendored MarmotKit bundle.
/// Regenerated by whitenoise-mac/scripts/sync-bindings.sh on every rebuild.
public enum MarmotKitVersion {
    public static let darkmatterSHA = "${DM_SHA}${DM_DIRTY}"
    public static let builtAt = "${BUILT_AT}"
    public static let uniffiVersion = "0.28.3"
}
EOF

echo ""
echo "Done. Vendored MarmotKit @ ${DM_SHA}${DM_DIRTY} (${DM_BRANCH})."
