#!/usr/bin/env bash
# Rebuild the MarmotKit bindings from the MDK Rust workspace and
# re-vendor them into this macOS app.
#
# Usage:
#   ./scripts/sync-bindings.sh
#   MDK_DIR=/path/to/mdk ./scripts/sync-bindings.sh

set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MDK_DIR="${MDK_DIR:-$HOME/code/mdk}"

CRATE_DIR="$MDK_DIR/crates/marmot-uniffi"
TARGET_DIR="${CARGO_TARGET_DIR:-$MDK_DIR/target}"
VENDOR_DIR="$APP_DIR/Vendored/MarmotKit"
BUILD_DIR="$(mktemp -d "${TMPDIR:-/tmp}/marmotkit-macos.XXXXXX")"
trap 'rm -rf "$BUILD_DIR"' EXIT

CRATE_NAME="marmot-uniffi"
LIB_BASENAME="marmot_uniffi"
FRAMEWORK_NAME="MarmotKit"
MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-15.6}"

if [[ ! -d "$CRATE_DIR" ]]; then
    echo "error: can't find marmot-uniffi crate at $CRATE_DIR" >&2
    echo "       set MDK_DIR to point at the mdk repo." >&2
    exit 1
fi

export PATH="$HOME/.cargo/bin:$PATH"
export MACOSX_DEPLOYMENT_TARGET
export CFLAGS_aarch64_apple_darwin="${CFLAGS_aarch64_apple_darwin:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}}"
export CXXFLAGS_aarch64_apple_darwin="${CXXFLAGS_aarch64_apple_darwin:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}}"
export RUSTFLAGS="${RUSTFLAGS:-} -C link-arg=-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}"

mkdir -p "$BUILD_DIR/headers" "$BUILD_DIR/swift" "$VENDOR_DIR/Sources/MarmotKit"

ENDPOINTS_ENV="$CRATE_DIR/marmotkit-endpoints.env"
if [[ -f "$ENDPOINTS_ENV" ]]; then
    # Public route defaults are compiled into MarmotKit; host apps provide tokens.
    # shellcheck source=/dev/null
    source "$ENDPOINTS_ENV"
fi

echo "==> Building host MarmotKit artifacts from $MDK_DIR"
(
    cd "$MDK_DIR"
    cargo build --release -p "$CRATE_NAME"
    cargo run --release -p "$CRATE_NAME" --features cli --bin uniffi-bindgen -- \
      generate \
      --library "$TARGET_DIR/release/lib${LIB_BASENAME}.dylib" \
      --language swift \
      --out-dir "$BUILD_DIR/swift"
)

echo "==> Staging headers + modulemap"
cp "$BUILD_DIR/swift/${LIB_BASENAME}FFI.h" "$BUILD_DIR/headers/"
cp "$BUILD_DIR/swift/${LIB_BASENAME}FFI.modulemap" "$BUILD_DIR/headers/module.modulemap"

echo "==> Stripping release debug symbols"
STATIC_LIB="$BUILD_DIR/lib${LIB_BASENAME}.a"
cp "$TARGET_DIR/release/lib${LIB_BASENAME}.a" "$STATIC_LIB"
xcrun strip -S "$STATIC_LIB"

echo "==> Creating macOS $FRAMEWORK_NAME.xcframework"
rm -rf "$VENDOR_DIR/$FRAMEWORK_NAME.xcframework"
xcodebuild -create-xcframework \
  -library "$STATIC_LIB" \
  -headers "$BUILD_DIR/headers" \
  -output "$VENDOR_DIR/$FRAMEWORK_NAME.xcframework"

echo "==> Copying generated Swift bindings"
cp "$BUILD_DIR/swift/${LIB_BASENAME}.swift" "$VENDOR_DIR/Sources/MarmotKit/$FRAMEWORK_NAME.swift"

echo "==> Stamping MARMOT_VERSION"
MDK_SHA="$(git -C "$MDK_DIR" rev-parse --short HEAD)"
MDK_BRANCH="$(git -C "$MDK_DIR" rev-parse --abbrev-ref HEAD)"
MDK_DIRTY=""
if ! git -C "$MDK_DIR" diff --quiet || ! git -C "$MDK_DIR" diff --cached --quiet; then
    MDK_DIRTY="-dirty"
fi
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$VENDOR_DIR/MARMOT_VERSION" <<EOF
mdk-sha: ${MDK_SHA}${MDK_DIRTY}
mdk-branch: ${MDK_BRANCH}
built-at: ${BUILT_AT}
uniffi-version: 0.28.3
macos-targets: aarch64-apple-darwin
macos-deployment-target: ${MACOSX_DEPLOYMENT_TARGET}

Notes:
- Regenerate with: whitenoise-mac/scripts/sync-bindings.sh
- A "-dirty" suffix means the mdk working tree had uncommitted
  changes when this bundle was built.
EOF

cat > "$VENDOR_DIR/Sources/MarmotKit/MarmotKitVersion.swift" <<EOF
import Foundation

/// Build-time provenance for this vendored MarmotKit bundle.
/// Regenerated by whitenoise-mac/scripts/sync-bindings.sh on every rebuild.
public enum MarmotKitVersion {
    public static let mdkSHA = "${MDK_SHA}${MDK_DIRTY}"
    public static let builtAt = "${BUILT_AT}"
    public static let uniffiVersion = "0.28.3"
}
EOF

echo ""
echo "Done. Vendored MarmotKit @ ${MDK_SHA}${MDK_DIRTY} (${MDK_BRANCH})."
